"""empty message

Revision ID: a5ba17b84808
Revises: e2f054e3224d
Create Date: 2021-01-29 15:55:07.307743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ba17b84808'
down_revision = 'e2f054e3224d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_request',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_url', sa.Unicode(), nullable=False),
    sa.Column('request_method', sa.Unicode(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.LargeBinary(), nullable=True),
    sa.Column('response_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.LargeBinary(), nullable=True),
    sa.Column('elapsed_time', sa.Interval(), nullable=True),
    sa.Column('exception', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incoming_request_id'), 'incoming_request', ['id'], unique=False)
    op.create_index(op.f('ix_incoming_request_request_datetime'), 'incoming_request', ['request_datetime'], unique=False)
    op.create_index(op.f('ix_incoming_request_request_method'), 'incoming_request', ['request_method'], unique=False)
    op.create_index(op.f('ix_incoming_request_request_url'), 'incoming_request', ['request_url'], unique=False)
    op.create_index(op.f('ix_incoming_request_response_datetime'), 'incoming_request', ['response_datetime'], unique=False)
    op.create_index(op.f('ix_incoming_request_response_status_code'), 'incoming_request', ['response_status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incoming_request_response_status_code'), table_name='incoming_request')
    op.drop_index(op.f('ix_incoming_request_response_datetime'), table_name='incoming_request')
    op.drop_index(op.f('ix_incoming_request_request_url'), table_name='incoming_request')
    op.drop_index(op.f('ix_incoming_request_request_method'), table_name='incoming_request')
    op.drop_index(op.f('ix_incoming_request_request_datetime'), table_name='incoming_request')
    op.drop_index(op.f('ix_incoming_request_id'), table_name='incoming_request')
    op.drop_table('incoming_request')
    # ### end Alembic commands ###
