"""empty message

Revision ID: c34182544b77
Revises: 40a2994f68af
Create Date: 2021-02-11 14:09:27.925010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34182544b77'
down_revision = '40a2994f68af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_client',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Unicode(), nullable=False),
    sa.Column('last_name', sa.Unicode(), nullable=False),
    sa.Column('country', sa.Unicode(), nullable=False),
    sa.Column('phone', sa.Unicode(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profile_client_country'), 'profile_client', ['country'], unique=False)
    op.create_index(op.f('ix_profile_client_first_name'), 'profile_client', ['first_name'], unique=False)
    op.create_index(op.f('ix_profile_client_last_name'), 'profile_client', ['last_name'], unique=False)
    op.create_index(op.f('ix_profile_client_phone'), 'profile_client', ['phone'], unique=False)
    op.create_table('profile_executor',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Unicode(), nullable=False),
    sa.Column('last_name', sa.Unicode(), nullable=False),
    sa.Column('country', sa.Unicode(), nullable=False),
    sa.Column('phone', sa.Unicode(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profile_executor_country'), 'profile_executor', ['country'], unique=False)
    op.create_index(op.f('ix_profile_executor_first_name'), 'profile_executor', ['first_name'], unique=False)
    op.create_index(op.f('ix_profile_executor_last_name'), 'profile_executor', ['last_name'], unique=False)
    op.create_index(op.f('ix_profile_executor_phone'), 'profile_executor', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_executor_phone'), table_name='profile_executor')
    op.drop_index(op.f('ix_profile_executor_last_name'), table_name='profile_executor')
    op.drop_index(op.f('ix_profile_executor_first_name'), table_name='profile_executor')
    op.drop_index(op.f('ix_profile_executor_country'), table_name='profile_executor')
    op.drop_table('profile_executor')
    op.drop_index(op.f('ix_profile_client_phone'), table_name='profile_client')
    op.drop_index(op.f('ix_profile_client_last_name'), table_name='profile_client')
    op.drop_index(op.f('ix_profile_client_first_name'), table_name='profile_client')
    op.drop_index(op.f('ix_profile_client_country'), table_name='profile_client')
    op.drop_table('profile_client')
    # ### end Alembic commands ###
